### ISSUE TITLE
Cells without data constraints on state

### ISSUE THREAD

**Issue by walseb** [turion/essence-of-live-coding#104]
Hi! Is there any way to disable data migration for certain cell functions so state doesn't need the `Data` constraint? Specifically I need `delay :: (Data s, Monad m) => s -> Cell m s s` to become `delay :: (Monad m) => s -> Cell m s s`. 

I need it because I'm having trouble defining data instances for some of my data types (due to some GADTs [being difficult to derive data from](https://stackoverflow.com/questions/12573669/how-can-i-derive-a-data-instance-for-a-gadt-in-haskell)). I don't mind them being reset to their default value on every migration. 

I think I can do this using the `Handle` mechanism by storing the GADT in a `MVar` or `Foreign.Store`. That way I only need to store the mvar/store handle in the cell state which has a data instance. Is there an easier way of doing this? Thanks!

**Comment by miguel-negrao** [comment]
Hi ! Yes, this was merged recently. Check [here](https://github.com/turion/essence-of-live-coding/blob/master/essence-of-live-coding/src/LiveCoding/Migrate/NoMigration.hs)

**Comment by miguel-negrao** [comment]
@turion I think this can be closed ?

**Comment by turion** [comment]
Yes, thanks :) @walseb feel free to reopen if this doesn't resolve the issue for you.

**Comment by walseb** [comment]
Awesome, thank you! Tangentially, does anyone know how to derive `Data` from this GADT? 
```haskell
data Foo a where
  Bar :: Foo Double
  Baz :: Foo Bool

deriving instance (Data a) => Data (Foo a) -- Doesn't work unless GADT only has a single constructor or have the same type of parameter `a`
```

**Comment by turion** [comment]
No, but I wouldn't expect such an instance to exist. After all, there is no way how to use the `Data a` instance in the `Data (Foo a)` instance.

**Comment by walseb** [comment]
I see so you don't think there is a way to derive data for GADTs like that?

**Comment by turion** [comment]
Not the way you wrote it. I didn't try it, but maybe `deriving instance Data (Foo Double)` and `deriving instance Data (Foo Bool)` work, or even `deriving instance Data (Foo a)`?

**Comment by walseb** [comment]
Thank you! I will see if I can get it to work next time when I might really need a data instance.
