### ISSUE TITLE
Remove vivid backend if it doesn't update

### ISSUE THREAD

**Issue by turion** [turion/essence-of-live-coding#131]
It is a nuisance to carry around the backend to https://hackage.haskell.org/package/vivid, because the maintainer doesn't update it to GHC 9.6. If no sign of maintenance appears in the next time, we should remove it, potentially putting it in its own repo. @miguel-negrao

**Comment by miguel-negrao** [comment]
Yes, unfortunately, I agree.

**Comment by miguel-negrao** [comment]
Vivid now builds in 9.10.1 (and imagine lower too).

**Comment by miguel-negrao** [comment]
I believe this can be closed.
