### ISSUE TITLE
Add Traversing instance to Cell

### ISSUE THREAD

**Issue by turion** [turion/essence-of-live-coding#57]
Follow-up to #56.

I think that Cells should be an instance of https://hackage.haskell.org/package/profunctors-5.6.2/docs/Data-Profunctor-Traversing.html#t:Traversing. Basically, this means that there should be a function `traverse' :: Traversable f => Cell m a b -> Cell m (f a) (f b)`. For example, a cell can be lifted into a cell of lists, or a cell of trees.

## To do

* Add `Choice` instance
* Add `Strong` instance
* Add `Traversing` instance, probably implementing `wander` and not `traverse'`

**Comment by miguel-negrao** [comment]
I think `WrappedArrow Cell` is already an instance of Traversing since Cell is an instance of Arrow and ArrowChoice.

**Comment by turion** [comment]
Where is such an instance defined?

**Comment by miguel-negrao** [comment]
Ah, actually, no, not quite. The Choice and Strong we don't have to implement, but we still have to implement the Traversing instance.

**Comment by miguel-negrao** [comment]
I didn't test this, only check that compiled, but I think Cell can be instance of Profunctor, Strong and Choice like below. I'm using coerce just for speed (If I understoddo correctly, coerce is an optimization):

```Haskell
{-# LANGUAGE InstanceSigs #-}
{-# LANGUAGE ScopedTypeVariables #-}

import Data.Profunctor
import Data.Profunctor.Strong
import Data.Profunctor.Choice
import Data.Profunctor.Traversing
import Data.Coerce

instance Monad m => Profunctor (Cell m) where
  dimap :: forall a b c d .(a -> b) -> (c -> d) -> Cell m b c -> Cell m a d
  dimap f g a = coerce $ dimap f g (coerce a :: WrappedArrow (Cell m) b c)

instance Monad m => Strong (Cell m) where
  first' :: forall a b c . Cell m a b -> Cell m (a, c) (b, c)
  first' a = coerce $ first' (coerce a :: WrappedArrow (Cell m) a b) 

instance Monad m => Data.Profunctor.Choice.Choice (Cell m) where
  left' :: forall a b c . Cell m a b -> Cell m (Either a c) (Either b c)
  left' a = coerce $ left' (coerce a :: WrappedArrow (Cell m) a b) 
```
My attempt at a Traversing instance. I'm using the first single state from the original cell to feed the function on the first tick, generating multiple output values. On subsequent ticks we use the multiple states stored in an `f s`.
```Haskell
instance (Monad m) => Traversing (Cell m) where
  traverse' :: Traversable f => Cell m a b -> Cell m (f a) (f b)
  traverse' (Cell s step) = Cell cellState' cellStep' where
    cellState' = Left s
    cellStep' (Left s) xs = fmap ((fmap fst) &&& (Right . (fmap snd))) $ traverse (step s) xs
    cellStep' (Right ys) xs = fmap ((fmap fst) &&& (Right . (fmap snd))) $ sequence $ step <$> ys <*> xs
  traverse' (ArrM f) = ArrM (traverse f)
```
The problem is that we need for `f s` to have a data Instance:

```
Could not deduce (Data (f s)) arising from a use of ‘Cell’
```
Do you see any way around this ?

**Comment by turion** [comment]
>  I'm using [coerce](https://hackage.haskell.org/package/base-4.15.0.0/docs/Data-Coerce.html) just for speed (If I understood correctly, coerce is an optimization):

I doubt this is necessary. `WrappedArrow` is a `newtype`, so it will be optimized away in the same manner as `coerce`, but it is typesafe.

**Comment by turion** [comment]
By the way, a pull request will simplify the discussio n;)

**Comment by miguel-negrao** [comment]
> I doubt this is necessary. `WrappedArrow` is a `newtype`, so it will be optimized away in the same manner as `coerce`, but it is typesafe.

But my understanding was that coerce is typesafe: ["The function coerce allows you to safely convert between values of types that have the same representation with no run-time overhead."](https://hackage.haskell.org/package/base-4.15.0.0/docs/Data-Coerce.html). Only instances of the `Coercible` type class can be converted, and I believe this typeclass is "magic" in the sense it is the compiler that decides which types are instances of it according to "if the compiler can infer that they have the same representation". 

In the [paper](http://research.microsoft.com/en-us/um/people/simonpj/papers/ext-f/coercible.pdf) from 2014, if I'm reading it correctly it claims that wrapping and unwrapping in a newtype has a runtime cost (page 1):

```
To get the resulting [HTML] we are forced to map Mk over
the list. Operationally, this map is the identity function –
the run-time representation of [String] is identical to [HTML]
– but it will carry a run-time cost nevertheless. The optimiser
in the Glasgow Haskell Compiler (GHC) is powerless to
fix the problem, because it works over a typed intermediate
language; the Mk constructor changes the type of its operand,
and hence cannot be optimised away.
```
I believe also that [DerivingVia](https://ghc.gitlab.haskell.org/ghc/doc/users_guide/exts/deriving_via.html) and GeneralisedNewtypeDeriving are now implemented using coerce. Actually the instances I did by hand can be derived automatically:

```Haskell
deriving via (WrappedArrow (Cell m)) instance Monad m => Profunctor (Cell m) 
deriving via (WrappedArrow (Cell m)) instance Monad m => Strong (Cell m)
deriving via (WrappedArrow (Cell m)) instance Monad m => Data.Profunctor.Choice.Choice (Cell m) 
```
ps: Will do a pull request on the above next.

**Comment by miguel-negrao** [comment]
> In your approach you would have to ask for a constraint `(Data s => Data (f s))`. (A better solution would be a `Data1` typeclass similar to https://hackage.haskell.org/package/base-4.15.0.0/docs/Data-Functor-Classes.html if it existed, but unfortunately it doesn't.) But that isn't possible because the type class `Traversing` controls what constraints you get on `f`, and this one isn't part of it.
> 
> I'm confused about your instance though. If you remember https://hackage.haskell.org/package/essence-of-live-coding-0.2.5/docs/src/LiveCoding.Cell.Resample.html#resampleList, it doesn't need to change the state type of the cell. The only thing that changes is the `cellStep`. The challenge is to express both list construction and folding through `Traversable`.

Actually my code above doesn't work, I'm assuming that f is Applicative when it is only Traversable. I can't use `<*>` :-(. I'm not seeing a way then to combine xs and ys with a `zipWith` like function.

I was changing the state type because I was assuming we wanted to run n copies of the arrow in "paralel", that is each one with it's own state. If the state is shared between applications of the arrow to each input, and using StateT, then it might be as simple as this (the following at least compiles):

```Haskell
data Cell2 m a b = forall s . Data s => Cell2
  { cellState2 :: s
  , cellStep2  :: a -> StateT s m b
  }
  | ArrM2 { runArrM2 :: a -> m b }

--instance (Monad m) => Traversing (Cell2 m) where
traverse' :: (Traversable f, Monad m) => Cell2 m a b -> Cell2 m (f a) (f b)
traverse' (Cell2 s step) = Cell2 cellState' cellStep' where
  cellState' = s
  cellStep' = traverse step
traverse' (ArrM2 f) = ArrM2 (traverse f)
```
But this traverse' above is indeed like resampleList, it's processing the input container in sequence. I think it is more interesting to process the input sequence in parallel like we do with the functions in arrow-utils. That is what I was trying to do in my first (failed) attempt. It's two different concepts, each one with it's utility. Not sure which one would be the "correct" one for a Traversing instance, don't have enough intuition about Traversing.

**Comment by turion** [comment]
> But this traverse' above is indeed like resampleList, it's processing the input container in sequence.

Yes, and that is the desired instance for `Cell`s, I think. It's useful for resampling. I often had the need of something like this. `resampleList` and `resampleMaybe` are special cases of it.

> I think it is more interesting to process the input sequence in parallel like we do with the functions in arrow-utils.

That is also an interesting function, but I think it's a special (or at least related) case of some [`sequenceArrList`](https://github.com/miguel-negrao/arrow-utils/blob/201d8755fff0fd1eeb77bfd6084ad847c8a39d98/src/Control/Arrow/Utils.hs#L72) function where we duplicate the cell.

> Not sure which one would be the "correct" one for a Traversing instance, don't have enough intuition about Traversing.

We could try and figure out which laws hold: https://hackage.haskell.org/package/profunctors-5.6.2/docs/Data-Profunctor-Traversing.html#v:traverse-39-

```haskell
traverse' . rmap f ≡ rmap (fmap f) . traverse'
traverse' . traverse' ≡ dimap Compose getCompose . traverse'
dimap Identity runIdentity . traverse' ≡ id
```

But on first glance I believe that both implementations satisfy them.

**Comment by miguel-negrao** [comment]
> > But this traverse' above is indeed like resampleList, it's processing the input container in sequence.
> 
> Yes, and that is the desired instance for `Cell`s, I think. It's useful for resampling. I often had the need of something like this. `resampleList` and `resampleMaybe` are special cases of it.

Ok, in that case indeed using StateT makes it easier to define.
> 
> > I think it is more interesting to process the input sequence in parallel like we do with the functions in arrow-utils.
> 
> That is also an interesting function, but I think it's a special (or at least related) case of some [`sequenceArrList`](https://github.com/miguel-negrao/arrow-utils/blob/201d8755fff0fd1eeb77bfd6084ad847c8a39d98/src/Control/Arrow/Utils.hs#L72) function where we duplicate the cell.
> 

Yes, it does look similar, but I still haven't figured out if `sequenceArrList` can be generalized for Traversables. I'm starting to suspect that it can't. In any case, I don't have a working version of the "parallel" approach for traverse'.

> > Not sure which one would be the "correct" one for a Traversing instance, don't have enough intuition about Traversing.
> 
> We could try and figure out which laws hold: https://hackage.haskell.org/package/profunctors-5.6.2/docs/Data-Profunctor-Traversing.html#v:traverse-39-
> 
> ```haskell
> traverse' . rmap f ≡ rmap (fmap f) . traverse'
> traverse' . traverse' ≡ dimap Compose getCompose . traverse'
> dimap Identity runIdentity . traverse' ≡ id
> ```
> 
> But on first glance I believe that both implementations satisfy them.

Right, we should prove the the traverse' (for Cell2 above) holds these laws.

**Comment by turion** [comment]
> > > But this traverse' above is indeed like resampleList, it's processing the input container in sequence.
> > 
> > 
> > Yes, and that is the desired instance for `Cell`s, I think. It's useful for resampling. I often had the need of something like this. `resampleList` and `resampleMaybe` are special cases of it.
> 
> Ok, in that case indeed using StateT makes it easier to define.

Another advantage is that this `traverse'` has a much better memory footprint. The other `traverse'` will take up as much memory as the biggest list that ever entered, and never shrink again.

> > > I think it is more interesting to process the input sequence in parallel like we do with the functions in arrow-utils.
> > 
> > 
> > That is also an interesting function, but I think it's a special (or at least related) case of some [`sequenceArrList`](https://github.com/miguel-negrao/arrow-utils/blob/201d8755fff0fd1eeb77bfd6084ad847c8a39d98/src/Control/Arrow/Utils.hs#L72) function where we duplicate the cell.
> 
> Yes, it does look similar, but I still haven't figured out if `sequenceArrList` can be generalized for Traversables. I'm starting to suspect that it can't. In any case, I don't have a working version of the "parallel" approach for traverse'.

Maybe not for general arrows. But for cells! If you have an `f (Cell m a b)`, you could in principle traverse it on `cellState` to get a state `f s`, and do a similar trick for `cellStep`. But the challenge would be that all states are of a different type, and one would need to put them in a `data DataBox where DataBox :: Data s => s -> DataBox`.

> > > Not sure which one would be the "correct" one for a Traversing instance, don't have enough intuition about Traversing.
> > 
> > 
> > We could try and figure out which laws hold: https://hackage.haskell.org/package/profunctors-5.6.2/docs/Data-Profunctor-Traversing.html#v:traverse-39-
> > ```haskell
> > traverse' . rmap f ≡ rmap (fmap f) . traverse'
> > traverse' . traverse' ≡ dimap Compose getCompose . traverse'
> > dimap Identity runIdentity . traverse' ≡ id
> > ```
> >   
> > But on first glance I believe that both implementations satisfy them.
> 
> Right, we should prove the the traverse' (for Cell2 above) holds these laws.

Since you really write `cellStep' = traverse step`, the laws must hold since they hold for `Kleisli`.
