### ISSUE TITLE
Support stack

### ISSUE THREAD

**Issue by turion** [turion/essence-of-live-coding#62]
* [x] Set up CI to build the project with stack, in a few past snapshots
* [x] Fix possible build errors

@miguel-negrao I likely won't work on this any time soon, but be my guest in case you want to submit a PR :)

**Comment by miguel-negrao** [comment]
Is there anything left to be done on this issue ?

**Comment by turion** [comment]
No, it's done. Thanks for your help on this in #69 and #72 :)
